version: '3'

services:

  parity:
    build: .
    volumes:
      - ./data:/data

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    depends_on:
      - parity

  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000
    depends_on:
      - parity

  explorer:
    image: jpoon/etherchain-light
    volumes:
      - ./explorer/config.js:/usr/src/app/config.js:ro
      - ./data:/data
    ports:
      - 3002:3000
    depends_on:
      - parity
