version: '3'

services: 
  parity: 
    image: parity/parity:v1.9.4
    ports: 
      - 8545
      - 8546
    command: --config /config/node.toml
    volumes: 
      - ./config:/config:ro
    networks:
      - nnet

networks:
  nnet:
