[parity]
chain = "./spec.json"
base_path = "/data"
db_path = "/data/chains"
keys_path = "/data/keys"

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal"]
processing_threads = 4

[ipc]
disable = false
path = "/data/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]

[websockets]
interface = "0.0.0.0"
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "pubsub"]

[footprint]
fat_db = "on"
pruning = "archive"

[network]
reserved_peers = "./bootnodes.txt"

[ui]
interface = "127.0.0.1"
port = 8180
